stages:
  - build
  - test
  - style

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.nix:
  tags:
    - nix

## Build stage #################################################################
.build:
  stage: build
  extends: .nix
  script:
    - "nix build .#$ARG"

bigclown-gateway:
  extends: .build
  variables:
    ARG: bigclown-gateway

bigclown-mqtt2influxdb:
  extends: .build
  variables:
    ARG: bigclown-mqtt2influxdb

bigclown-firmware-tool:
  extends: .build
  variables:
    ARG: bigclown-firmware-tool

bigclown-control-tool:
  extends: .build
  variables:
    ARG: bigclown-control-tool

## Test stage ##################################################################

nix-check:
  stage: test
  extends: .nix
  script:
    - nix flake check

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

## Style stage #################################################################

nixfmt:
  stage: style
  extends: .nix
  allow_failure: true
  script:
    - "nix fmt"
    - "git diff --exit-code"
